name: mangadexapi
description: "A new Dart package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  dart_mappable: ^4.5.0
  http: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
  lints: ^5.1.1
